name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          brew install swiftlint
          npm install create-dmg

      - name: Build app
        run: |
          xcodebuild \
            -project Spwifiy.xcodeproj \
            -scheme Spwifiy \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            -derivedDataPath .build

      - name: Create dmg
        run: |
          npx create-dmg \
            --overwrite \
            --no-code-sign \
            --no-version-in-filename \
            .build/Build/Products/Release/Spwifiy.app \
            ./

      - name: Upload dmg
        uses: actions/upload-artifact@v7
        with:
          name: Spwifiy.dmg
          path: ./*.dmg
